
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: devuser
  password: devpass
  host: localhost

development:
  <<: *default
  database: crmimg_development
  username: devuser
  password: devpass
  #host: localhost

test:
  <<: *default
  database: crmimg_test
  username: devuser
  password: devpass
  #host: localhost


production:
  <<: *default
  database: crmimg_production
  username: crmimg
  password: <%= ENV['CRMIMG_DATABASE_PASSWORD'] %>
