
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: devuser
  password: devpass

development:
  <<: *default
  database: crmimg_development

test:
  <<: *default
  database: crmimg_test


production:
  <<: *default
  database: crmimg_production
  username: crmimg
  password: <%= ENV['CRMIMG_DATABASE_PASSWORD'] %>
